In [1]:
import tensorflow as tf


In [2]:
import tensorflow as tf
v1 = tf.l(a1, b1)
v2 = tf.logical_and(a2, b2)

NameError: name 'a1' is not defined

In [5]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([1,2,3])
c=tf.reduce_mean(a)

print(c)

Tensor("Mean:0", shape=(), dtype=int32)


In [6]:


import tensorflow as tf
import tensorflow as tf
x=tf.constant([1.0,2.0,3.0,4.0],shape=[1,4],name='x')
y=tf.constant([5.0,6.0,7.0,8.0],shape=[1,4],name='y')
with tf.name_scope("mean"):
    with tf.name_scope("mean_x_y"):
        x1=tf.reduce_mean(x)
        y1=tf.reduce_mean(y)
        sess=tf.Session()
    print(sess.run(x1))
    print(sess.run(y1))
with tf.name_scope("variance"):
    with tf.name_scope("scope_sub1"):
        a=tf.subtract(x,x1)
        sess1=tf.Session()
    print(sess1.run(a))
    with tf.name_scope("scope_sub2"):
        b=tf.subtract(y,y1)
        sess2=tf.Session()
    print(sess2.run(b))
    with tf.name_scope("scope_square"):
        a1=tf.multiply(a,a)
        sess3=tf.Session()
    print(sess3.run(a1))
    with tf.name_scope("scope_summation"):
        var=tf.reduce_sum(a1)
        sess4=tf.Session()
    print(sess4.run(var))
with tf.name_scope("covariance"):
    with tf.name_scope("multiplication"):
        mul1=tf.multiply(a,b)
        sess5=tf.Session()
    print(sess5.run(mul1))
    with tf.name_scope("scope_summation2"):
        covar=tf.reduce_sum(mul1)
        sess6=tf.Session()
    print(sess6.run(covar))

2.5
6.5
[[-1.5 -0.5  0.5  1.5]]
[[-1.5 -0.5  0.5  1.5]]
[[ 2.25  0.25  0.25  2.25]]
5.0
[[ 2.25  0.25  0.25  2.25]]
5.0
